"""first migrate

Revision ID: 39e3e919d70d
Revises: 
Create Date: 2019-06-03 23:28:41.805397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e3e919d70d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('subject',
    sa.Column('sub_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('sub_id')
    )
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    op.create_table('type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_type_type_name'), 'type', ['type_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_table('student',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('std_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('grp_name', sa.String(length=255), nullable=True),
    sa.Column('u_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['grp_name'], ['group.name'], ),
    sa.ForeignKeyConstraint(['std_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_student_name'), 'student', ['name'], unique=False)
    op.create_index(op.f('ix_student_u_id'), 'student', ['u_id'], unique=True)
    op.create_table('teacher',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('teach_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sub_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sub_name'], ['subject.name'], ),
    sa.ForeignKeyConstraint(['teach_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('row_id')
    )
    op.create_index(op.f('ix_teacher_name'), 'teacher', ['name'], unique=True)
    op.create_table('session',
    sa.Column('ses_id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=255), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('teach_name', sa.String(length=255), nullable=True),
    sa.Column('ses_type', sa.String(length=255), nullable=True),
    sa.Column('u_id', sa.String(length=255), nullable=True),
    sa.Column('sem_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ses_type'], ['type.type_name'], ),
    sa.ForeignKeyConstraint(['sub_name'], ['subject.name'], ),
    sa.ForeignKeyConstraint(['teach_name'], ['teacher.name'], ),
    sa.ForeignKeyConstraint(['u_id'], ['student.u_id'], ),
    sa.PrimaryKeyConstraint('ses_id')
    )
    op.create_index(op.f('ix_session_data'), 'session', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_data'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_teacher_name'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_u_id'), table_name='student')
    op.drop_index(op.f('ix_student_name'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_type_type_name'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
